# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80bbe1fcf6503c84cfb00805ddbd32dd27c70711326ed6e4e2f2c1ec26e4f46aa5e0661d48458448600aa6630d8dca0d10597ab550d0f81c345ce5ec14f81103

test:
  secret_key_base: e9ae3ca2d6cf890dafa9aabe6a97b326833fa757c85c9565b0e06072252963e5b8ce496f0d52a9f3eabaeeec4e798f5a219b58714e721af4243cb8afd3b67eb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
